apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NeholiukVadim/content-gitops.git'
    targetRevision: HEAD
    path: workloads # Path to your Kubernetes manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true